version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# Tutorial at https://github.com/Mad-Chicken/pihole-docker
services:
  pihole:
    container_name: pihole
    image: my_pihole
    build:
      context: .
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      WEBPASSWORD: 'ADMIN-PASSWORD'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped